### ISSUE TITLE
OpenAPI documentation

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#251]
Investigate possible regression in https://raw.githubusercontent.com/hirosystems/chainhook/develop/docs/chainhook-openapi.json

**Comment by lgalabru** [comment]
Additionally:
```
servers:
  - url: https://api.hiro.so/
    description: mainnet
  - url: https://api.testnet.hiro.so/
    description: testnet
tags:
  - name: Tokens
    description: Token metadata endpoints
  - name: Status
    description: Service status endpoints
externalDocs:
  url: https://github.com/hirosystems/token-metadata-api
  description: Source Repository
```
