### ISSUE TITLE
Predicate status report notifications

### ISSUE THREAD

**Issue by lgalabru** [hirosystems/chainhook#434]
The Hiro platform includes a frontend tracking predicates status. 
To keep this frontend updated with predicates activities, we could implement a new setting, triggering callbacks to an http endpoint every-time a new block is being processed.

```toml
[network]
predicates_activity_reporting_webhook = "https://platform.cluster.local/api/internals/chainhook-reporting"
```

In this design, the platform could expose a POST HTTP endpoint that the chainhook node is notifying with a payload embedding predicate activities report, every time there is a new block discovered.
