### ISSUE TITLE
implement limits set in Chainhook.toml

### ISSUE THREAD

**Issue by MicaiahReid** [hirosystems/chainhook#533]
We have a limits section in the Chainhook.toml:
```toml
[limits]
max_number_of_bitcoin_predicates = 100
max_number_of_concurrent_bitcoin_scans = 100
max_number_of_stacks_predicates = 10
max_number_of_concurrent_stacks_scans = 10
max_number_of_processing_threads = 16
max_number_of_networking_threads = 16
max_caching_memory_size_mb = 32000
```
but most of these are not implemented. We also have a few hardcoded max retries throughout the code base. It would be great if we added all of these to the limits config as well.
